# Practice Assignment: Assignment Name
## Student: Joseph Lim

Task: Practice SQL Queries

## Import Libraries and Mount Drive if Necessary

In [1]:
import pandas as pd
from sqlalchemy import create_engine

pd.set_option('display.max_columns', None) #Used for displaying columns
pd.set_option('display.max_rows', None) #Used for displaying rows

In [2]:
# load data - change the path to match your drive!
df_details = pd.read_csv("School_Details.csv")
# make sure it loaded correctly
df_details.head(2)

,DistrictName,EstablishmentCode,EstablishmentName,BRCName,CRCName,SchoolLevel,ManagementName,LocalityHabitation,SubdivisionName,ConstituencyName,RevenueBlockName,CivicBodyName,WardName,PostOfficeName,PhoneNo,FaxNo,EmailID,Website,LocatedInRuralOrUrban,DiseCode,EstablishedDate,DistrictHQDistance (in Km),CRCDistance (in Km),BACDistance (in Km),IsRecognized,RecognizedBy,ContactPersonName,LowestClass,HighestClass,BoardName
0,East,S0169,BUDANG GOVERNMENT PRIMARY SCHOOL (E),Duga Brc,Central Pendam Government Senior Secondary School,PS,State Govt.,BUDANG,Gangtok,Rhenock,Central Pendam,Central Pendam,Sajong,Upper Pendam,NaN,NaN,NaN,NaN,Urban Area,NaN,28126,58.0,8.0,16.0,Recognized,HRDD,NaN,Class 1,Class 5,NaN
1,East,S0099,CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL,Duga Brc,Central Pendam Government Senior Secondary School,SSS,State Govt.,CENTRAL PENDAM,Gangtok,West Pandam,Central Pendam,Central Pendam,Karmithang,Upper Pendam,3592263812,NaN,NaN,NaN,Urban Area,800401,15342,50.0,0.0,6.0,Recognized,HRDD,NaN,Class 1,Class 12,C.B.S.E.

In [3]:
df_facility = pd.read_csv("School_Facility_Details.csv")
df_facility.head(2)

,EstablishmentCode,EstablishmentName,IsLibraryAvailable,AvailableBooksCount,IsFireExtgAvailable,ExtinguisherCount,HOIRoomAvailable,IsStaffRoomAvailable,NoofStaffRoom,IsLockerForStaffAvailable,IsSportsStoreRoomAvailable
0,S1034,(I.E.C) INDIAN EVANGALISTIC CRUSADE MISSION PR...,Not Available,0,Available,1,Available,Not Available,0,Not Available,Not Available
1,S0516,10TH MILE GOVERNMENT PRIMARY SCHOOL,Not Available,0,Not Available,0,Available,Available,1,Not Available,Not Available

In [4]:
# create sqlite engine for a database called schools
engine = create_engine('sqlite:///schools.db', echo=True)
# create connection to engine
conn = engine.connect()

In [5]:
# add the dataframe as a table in sqlite
sqlite_table1 = "school_details"
df_details.to_sql(sqlite_table1, conn, if_exists='fail')

sqlite_table2 = "school_facility_details"
df_facility.to_sql(sqlite_table2, conn, if_exists='fail')

2023-03-14 15:23:05,498 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("school_details")
2023-03-14 15:23:05,499 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-03-14 15:23:05,500 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("school_details")
2023-03-14 15:23:05,501 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-03-14 15:23:05,504 INFO sqlalchemy.engine.Engine
CREATE TABLE school_details (
	"index" BIGINT,
	"DistrictName" TEXT,
	"EstablishmentCode" TEXT,
	"EstablishmentName" TEXT,
	"BRCName" TEXT,
	"CRCName" TEXT,
	"SchoolLevel" TEXT,
	"ManagementName" TEXT,
	"LocalityHabitation" TEXT,
	"SubdivisionName" TEXT,
	"ConstituencyName" TEXT,
	"RevenueBlockName" TEXT,
	"CivicBodyName" TEXT,
	"WardName" TEXT,
	"PostOfficeName" TEXT,
	"PhoneNo" TEXT,
	"FaxNo" TEXT,
	"EmailID" TEXT,
	"Website" TEXT,
	"LocatedInRuralOrUrban" TEXT,
	"DiseCode" TEXT,
	"EstablishedDate" TEXT,
	"DistrictHQDistance (in Km)" FLOAT,
	"CRCDistance (in Km)" FLOAT,
	"BACDistance (in Km)" FLOAT,
	"IsRecognized" TEXT,
	"RecognizedBy" TEXT,
	"ContactPersonName" FLOAT,
	"LowestClass" TEXT,
	"HighestClass" TEXT,
	"BoardName" TEXT
)


2023-03-14 15:23:05,505 INFO sqlalchemy.engine.Engine [no key 0.00092s] ()
2023-03-14 15:23:05,507 INFO sqlalchemy.engine.Engine COMMIT
2023-03-14 15:23:05,508 INFO sqlalchemy.engine.Engine CREATE INDEX ix_school_details_index ON school_details ("index")
2023-03-14 15:23:05,509 INFO sqlalchemy.engine.Engine [no key 0.00078s] ()
2023-03-14 15:23:05,512 INFO sqlalchemy.engine.Engine COMMIT
2023-03-14 15:23:05,545 INFO sqlalchemy.engine.Engine INSERT INTO school_details ("index", "DistrictName", "EstablishmentCode", "EstablishmentName", "BRCName", "CRCName", "SchoolLevel", "ManagementName", "LocalityHabitation", "SubdivisionName", "ConstituencyName", "RevenueBlockName", "CivicBodyName", "WardName", "PostOfficeName", "PhoneNo", "FaxNo", "EmailID", "Website", "LocatedInRuralOrUrban", "DiseCode", "EstablishedDate", "DistrictHQDistance (in Km)", "CRCDistance (in Km)", "BACDistance (in Km)", "IsRecognized", "RecognizedBy", "ContactPersonName", "LowestClass", "HighestClass", "BoardName") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-03-14 15:23:05,546 INFO sqlalchemy.engine.Engine [generated in 0.02026s] ((0, 'East', 'S0169', 'BUDANG GOVERNMENT PRIMARY SCHOOL (E)', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'State Govt.', 'BUDANG', 'Gangtok', 'Rhenock', 'Central Pendam', 'Central Pendam', 'Sajong', 'Upper Pendam', None, None, None, None, 'Urban Area', None, '28126', 58.0, 8.0, 16.0, 'Recognized', 'HRDD', None, 'Class 1', 'Class 5', None), (1, 'East', 'S0099', 'CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'SSS', 'State Govt.', 'CENTRAL PENDAM', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Karmithang', 'Upper Pendam', '3592263812', None, None, None, 'Urban Area', '800401', '15342', 50.0, 0.0, 6.0, 'Recognized', 'HRDD', None, 'Class 1', 'Class 12', 'C.B.S.E.'), (2, 'East', 'S0848', 'CENTRAL POINT ACADEMY, CENTRAL PENDAM', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'SS', 'Private (Unaided)', 'UPPER BHURUNG CENTRAL PENDAM', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Burung', 'Upper Pendam', '03592263809/263960', None, 'ksu_5162@yahoo.com', 'www.facebook.com/khanalkeshav (Group-CPA)', 'Urban Area', None, '37257.38680555556', 49.0, 1.5, 6.0, 'Recognized', 'HRDD, GOVT. OF SIKKIM', None, 'Class 1', 'Class 10', 'C.B.S.E.'), (3, 'East', 'S0190', 'CHEURIBOTEY GOVERNMENT JUNIOR HIGH SCHOOL (E)', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'JHS', 'State Govt.', 'CHEURIBOTEY', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Cheuribotey', 'Duga', None, None, None, None, 'Urban Area', None, '28856', 60.0, 6.0, 6.0, 'Recognized', 'State Govt.', None, 'Class 1', 'Class 8', None), (4, 'East', 'S0111', 'DUGA GOVERNMENT SECONDARY SCHOOL', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'SS', 'State Govt.', 'DUGA', 'Gangtok', 'West Pandam', 'Central Pendam', 'Central Pendam', 'Duga', 'Duga', '9832082915', None, 'dugaschool@gmail.com', None, 'Urban Area', None, '1828', 52.0, 0.0, 0.5, 'Recognized', 'c.b.s.e.', None, 'Class 1', 'Class 10', 'C.B.S.E.'), (5, 'East', 'S0856', 'EASWARAMMA SAI GURUKOOL ACCADEMY', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'Private (Unaided)', 'RALUNG', 'Gangtok', 'West Pandam', 'Central Pendam', 'West Pendam', 'Ralang', 'West Pendam', '9733056624', None, None, None, 'Urban Area', None, '40179.66805555556', 0.0, 0.2, 0.2, 'Recognized', None, None, 'Class 1', 'Class 5', None), (6, 'East', 'S0870', 'ETERNAL ENGLISH SCHOOL, WEST PENDAM', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'Private (Unaided)', 'SAKHU WEST PENDAM', 'Gangtok', 'West Pandam', 'West Pendam', 'West Pendam', 'Sakhu', 'Sakhu Busty', '9734190544', None, None, None, 'Urban Area', None, '37300.66805555556', 42.0, 3.0, 4.0, 'Recognized', 'HRDD OF SIKKIM', None, 'Class 1', 'Class 5', None), (7, 'East', 'S0157', 'KHANI GOAN GOVERNMENT PRIMARY SCHOOL', 'Duga Brc', 'Central Pendam Government Senior Secondary School', 'PS', 'State Govt.', 'WEST PENDAM', 'Gangtok', 'West Pandam', 'West Pendam', 'West Pendam', 'Khanigaon', 'West Pendam', '9832470263', None, None, None, 'Urban Area', '801801', '29587', 45.0, 5.0, 4.0, 'Recognized', 'State Govt.', None, 'Class 1', 'Class 5', 'C.B.S.E.')  ... displaying 10 of 1249 total bound parameter sets ...  (1247, 'West', 'S0340', 'TINGTING GAON GOVERNMENT PRIMARY SCHOOL', 'Yuksom Brc', 'Yuksom Government Secondary School', 'PS', 'State Govt.', 'TING TING GAON', 'Gyalshing', 'Yoksam-Tashiding', 'Yoksam', 'Yuksom', 'Tingting', 'Yuksom', '9593377402', None, None, None, 'Urban Area', '100282', '29587', 36.0, 3.0, 6.0, 'Recognized', 'STATE GOVERNMENT', None, 'Class 1', 'Class 5', None), (1248, 'West', 'S0542', 'TSONG GOVERNMENT PRIMARY SCHOOL', 'Yuksom Brc', 'Yuksom Government Secondary School', 'PS', 'State Govt.', 'TSONG', 'Gyalshing', 'Yoksam-Tashiding', 'Yoksam', 'Yuksom', 'Yoksam', 'Yuksom', None, None, None, None, 'Urban Area', None, '28176', 40.0, 7.0, 8.0, 'Recognized', 'State Government', None, 'Class 1', 'Class 5', 'C.B.S.E.'))
2023-03-14 15:23:05,556 INFO sqlalchemy.engine.Engine COMMIT
2023-03-14 15:23:05,563 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("school_facility_details")
2023-03-14 15:23:05,564 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-03-14 15:23:05,565 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("school_facility_details")
2023-03-14 15:23:05,565 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-03-14 15:23:05,568 INFO sqlalchemy.engine.Engine
CREATE TABLE school_facility_details (
	"index" BIGINT,
	"EstablishmentCode" TEXT,
	"EstablishmentName" TEXT,
	"IsLibraryAvailable" TEXT,
	"AvailableBooksCount" BIGINT,
	"IsFireExtgAvailable" TEXT,
	"ExtinguisherCount" BIGINT,
	"HOIRoomAvailable" TEXT,
	"IsStaffRoomAvailable" TEXT,
	"NoofStaffRoom" BIGINT,
	"IsLockerForStaffAvailable" TEXT,
	"IsSportsStoreRoomAvailable" TEXT
)


2023-03-14 15:23:05,569 INFO sqlalchemy.engine.Engine [no key 0.00090s] ()
2023-03-14 15:23:05,570 INFO sqlalchemy.engine.Engine COMMIT
2023-03-14 15:23:05,571 INFO sqlalchemy.engine.Engine CREATE INDEX ix_school_facility_details_index ON school_facility_details ("index")
2023-03-14 15:23:05,572 INFO sqlalchemy.engine.Engine [no key 0.00070s] ()
2023-03-14 15:23:05,574 INFO sqlalchemy.engine.Engine COMMIT
2023-03-14 15:23:05,589 INFO sqlalchemy.engine.Engine INSERT INTO school_facility_details ("index", "EstablishmentCode", "EstablishmentName", "IsLibraryAvailable", "AvailableBooksCount", "IsFireExtgAvailable", "ExtinguisherCount", "HOIRoomAvailable", "IsStaffRoomAvailable", "NoofStaffRoom", "IsLockerForStaffAvailable", "IsSportsStoreRoomAvailable") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-03-14 15:23:05,589 INFO sqlalchemy.engine.Engine [generated in 0.00816s] ((0, 'S1034', '(I.E.C) INDIAN EVANGALISTIC CRUSADE MISSION PRIMARY SCHOOL, RIMBI', 'Not Available', 0, 'Available', 1, 'Available', 'Not Available', 0, 'Not Available', 'Not Available'), (1, 'S0516', '10TH MILE GOVERNMENT PRIMARY SCHOOL', 'Not Available', 0, 'Not Available', 0, 'Available', 'Available', 1, 'Not Available', 'Not Available'), (2, 'S0237', '4TH MILE GOVERNMENT JUNIOR HIGH SCHOOL', 'Not Available', 0, 'Available', 2, 'Not Available', 'Not Available', 0, 'Not Available', 'Not Available'), (3, 'S0692', 'AAPGAZI GOVERNMENT PRIMARY SCHOOL', 'Not Available', 0, 'Not Available', 0, 'Not Available', 'Not Available', 0, 'Not Available', 'Not Available'), (4, 'S0374', 'AARUBOTEY GOVERNMENT PRIMARY SCHOOL', 'Not Available', 0, 'Available', 2, 'Not Available', 'Not Available', 0, 'Not Available', 'Not Available'), (5, 'S0218', 'ADAMPOOL GOVERNMENT JUNIOR HIGH SCHOOL', 'Available', 217, 'Available', 5, 'Available', 'Available', 1, 'Available', 'Not Available'), (6, 'S1064', 'ADONAI HOMES , NAYA BAZAR', 'Available', 0, 'Available', 0, 'Not Available', 'Available', 2, 'Not Available', 'Available'), (7, 'C1348', 'ADVANCED TECHNICAL TRAINING CENTRE', 'Available', 0, 'Available', 0, 'Available', 'Available', 0, 'Available', 'Available')  ... displaying 10 of 1256 total bound parameter sets ...  (1254, 'S0185', 'ZITLANG GOVERNMENT JUNIOR HIGH SCHOOL', 'Available', 0, 'Available', 5, 'Not Available', 'Available', 1, 'Not Available', 'Not Available'), (1255, 'S0267', 'ZOOM GOVERNMENT SECONDARY SCHOOL', 'Not Available', 0, 'Available', 6, 'Available', 'Available', 1, 'Available', 'Not Available'))

2023-03-14 15:23:05,594 INFO sqlalchemy.engine.Engine COMMIT

1256

## Problems:

In [6]:
#What is the average BACDistance (in Km)? Rename the output column to "avg_bac_distance."
# Write your SQL query in this string
sql = """
SELECT AVG(`BACDistance (in KM)`) as avg_bac_distance
FROM school_details
"""
# Read the sql query into pandas to view the results
df = pd.read_sql_query(sql, engine)
df.head()

2023-03-14 15:34:39,935 INFO sqlalchemy.engine.Engine
SELECT AVG(`BACDistance (in KM)`) as avg_bac_distance
FROM school_details

2023-03-14 15:34:39,936 INFO sqlalchemy.engine.Engine [raw sql] ()

   avg_bac_distance
0         12.681822

In [9]:
# What is the average BACDistance (in Km) by School Level? 
# Sort the results from highest average to lowest average.

sql = """
SELECT AVG(`BACDistance (in KM)`) as avg_bac_distance_by_level, SchoolLevel
FROM school_details
GROUP BY SchoolLevel
"""
# Read the sql query into pandas to view the results
df = pd.read_sql_query(sql, engine)
df.head()

2023-03-14 15:36:39,066 INFO sqlalchemy.engine.Engine
SELECT AVG(`BACDistance (in KM)`) as avg_bac_distance_by_level, SchoolLevel
FROM school_details
GROUP BY SchoolLevel

2023-03-14 15:36:39,067 INFO sqlalchemy.engine.Engine [raw sql] ()

   avg_bac_distance_by_level SchoolLevel
0                        NaN        None
1                  13.692647         JHS
2                   5.368421         LPS
3                  12.830787          PS
4                  12.630872          SS

In [11]:
# Repeat the previous query, but only display results 
#where the average distance is at least 10 km.
sql = """
SELECT AVG(`BACDistance (in KM)`) as avg_bac_distance_by_level, SchoolLevel
FROM school_details
GROUP BY SchoolLevel
HAVING avg_bac_distance_by_level > 10
;
"""
# Read the sql query into pandas to view the results
df = pd.read_sql_query(sql, engine)
df.head()

2023-03-14 15:39:57,862 INFO sqlalchemy.engine.Engine
SELECT AVG(`BACDistance (in KM)`) as avg_bac_distance_by_level, SchoolLevel
FROM school_details
GROUP BY SchoolLevel
HAVING avg_bac_distance_by_level > 10
;

2023-03-14 15:39:57,863 INFO sqlalchemy.engine.Engine [raw sql] ()

   avg_bac_distance_by_level SchoolLevel
0                  13.692647         JHS
1                  12.830787          PS
2                  12.630872          SS
3                  10.863095         SSS

In [12]:
#Join the two tables together (school_details and school_facility_details). 
#Start by displaying all of the columns, but 
#limit the resulting rows to just 2.
sql = """
SELECT *
FROM school_details d INNER JOIN school_facility_details f 
ON d.EstablishmentCode = f.EstablishmentCode
LIMIT 2
;
"""
# Read the sql query into pandas to view the results
df = pd.read_sql_query(sql, engine)
df.head()

2023-03-14 15:42:59,721 INFO sqlalchemy.engine.Engine
SELECT *
FROM school_details d INNER JOIN school_facility_details f
ON d.EstablishmentCode = f.EstablishmentCode
LIMIT 2
;

2023-03-14 15:42:59,722 INFO sqlalchemy.engine.Engine [raw sql] ()

,index,DistrictName,EstablishmentCode,EstablishmentName,BRCName,CRCName,SchoolLevel,ManagementName,LocalityHabitation,SubdivisionName,ConstituencyName,RevenueBlockName,CivicBodyName,WardName,PostOfficeName,PhoneNo,FaxNo,EmailID,Website,LocatedInRuralOrUrban,DiseCode,EstablishedDate,DistrictHQDistance (in Km),CRCDistance (in Km),BACDistance (in Km),IsRecognized,RecognizedBy,ContactPersonName,LowestClass,HighestClass,BoardName,index,EstablishmentCode,EstablishmentName,IsLibraryAvailable,AvailableBooksCount,IsFireExtgAvailable,ExtinguisherCount,HOIRoomAvailable,IsStaffRoomAvailable,NoofStaffRoom,IsLockerForStaffAvailable,IsSportsStoreRoomAvailable
0,0,East,S0169,BUDANG GOVERNMENT PRIMARY SCHOOL (E),Duga Brc,Central Pendam Government Senior Secondary School,PS,State Govt.,BUDANG,Gangtok,Rhenock,Central Pendam,Central Pendam,Sajong,Upper Pendam,None,None,None,None,Urban Area,None,28126,58.0,8.0,16.0,Recognized,HRDD,None,Class 1,Class 5,None,121,S0169,BUDANG GOVERNMENT PRIMARY SCHOOL (E),Available,100,Available,2,Available,Available,1,Not Available,Not Available
1,1,East,S0099,CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL,Duga Brc,Central Pendam Government Senior Secondary School,SSS,State Govt.,CENTRAL PENDAM,Gangtok,West Pandam,Central Pendam,Central Pendam,Karmithang,Upper Pendam,3592263812,None,None,None,Urban Area,800401,15342,50.0,0.0,6.0,Recognized,HRDD,None,Class 1,Class 12,C.B.S.E.,137,S0099,CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL,Available,0,Available,5,Available,Available,2,Not Available,Available

In [13]:
# Select just the schools where the SchoolLevel is "PS" that do not have libraries.
sql = """
SELECT *
FROM school_details d INNER JOIN school_facility_details f 
ON d.EstablishmentCode = f.EstablishmentCode
WHERE SchoolLevel IS "PS" AND IsLibraryAvailable IS "Available"
;
"""
# Read the sql query into pandas to view the results
df = pd.read_sql_query(sql, engine)
df.head()

2023-03-14 15:45:43,381 INFO sqlalchemy.engine.Engine
SELECT *
FROM school_details d INNER JOIN school_facility_details f
ON d.EstablishmentCode = f.EstablishmentCode
WHERE SchoolLevel IS "PS" AND IsLibraryAvailable IS "Available"
;

2023-03-14 15:45:43,382 INFO sqlalchemy.engine.Engine [raw sql] ()

,index,DistrictName,EstablishmentCode,EstablishmentName,BRCName,CRCName,SchoolLevel,ManagementName,LocalityHabitation,SubdivisionName,ConstituencyName,RevenueBlockName,CivicBodyName,WardName,PostOfficeName,PhoneNo,FaxNo,EmailID,Website,LocatedInRuralOrUrban,DiseCode,EstablishedDate,DistrictHQDistance (in Km),CRCDistance (in Km),BACDistance (in Km),IsRecognized,RecognizedBy,ContactPersonName,LowestClass,HighestClass,BoardName,index,EstablishmentCode,EstablishmentName,IsLibraryAvailable,AvailableBooksCount,IsFireExtgAvailable,ExtinguisherCount,HOIRoomAvailable,IsStaffRoomAvailable,NoofStaffRoom,IsLockerForStaffAvailable,IsSportsStoreRoomAvailable
0,0,East,S0169,BUDANG GOVERNMENT PRIMARY SCHOOL (E),Duga Brc,Central Pendam Government Senior Secondary School,PS,State Govt.,BUDANG,Gangtok,Rhenock,Central Pendam,Central Pendam,Sajong,Upper Pendam,None,None,None,None,Urban Area,None,28126,58.0,8.0,16.0,Recognized,HRDD,None,Class 1,Class 5,None,121,S0169,BUDANG GOVERNMENT PRIMARY SCHOOL (E),Available,100,Available,2,Available,Available,1,Not Available,Not Available
1,6,East,S0870,"ETERNAL ENGLISH SCHOOL, WEST PENDAM",Duga Brc,Central Pendam Government Senior Secondary School,PS,Private (Unaided),SAKHU WEST PENDAM,Gangtok,West Pandam,West Pendam,West Pendam,Sakhu,Sakhu Busty,9734190544,None,None,None,Urban Area,None,37300.66805555556,42.0,3.0,4.0,Recognized,HRDD OF SIKKIM,None,Class 1,Class 5,None,248,S0870,"ETERNAL ENGLISH SCHOOL, WEST PENDAM",Available,0,Available,1,Not Available,Not Available,0,Not Available,Not Available
2,7,East,S0157,KHANI GOAN GOVERNMENT PRIMARY SCHOOL,Duga Brc,Central Pendam Government Senior Secondary School,PS,State Govt.,WEST PENDAM,Gangtok,West Pandam,West Pendam,West Pendam,Khanigaon,West Pendam,9832470263,None,None,None,Urban Area,801801,29587,45.0,5.0,4.0,Recognized,State Govt.,None,Class 1,Class 5,C.B.S.E.,407,S0157,KHANI GOAN GOVERNMENT PRIMARY SCHOOL,Available,60,Available,2,Not Available,Available,1,Available,Not Available
3,9,East,S0164,OKHARBOTEY GOVERNMENT PRIMARY SCHOOL,Duga Brc,Central Pendam Government Senior Secondary School,PS,State Govt.,OKHARBOTTEY,Gangtok,Namcheybong,Lingzey Sumen,Sumin Lingzey,Upper Linzey,West Pendam,9434174498,None,None,None,Urban Area,None,31413,70.0,4.0,9.0,Recognized,State Govt.,None,Class 1,Class 5,None,727,S0164,OKHARBOTEY GOVERNMENT PRIMARY SCHOOL,Available,20,Available,2,Available,Available,1,Not Available,Not Available
4,13,East,S0137,SAKHU KHANI GOVERNMENT PRIMARY SCHOOL,Duga Brc,Central Pendam Government Senior Secondary School,PS,State Govt.,SAKHU,Gangtok,West Pandam,Central Pendam,West Pendam,Sakhu,Sakhu Busty,9832352030,None,None,None,Urban Area,802001,25569,36.0,4.0,4.0,Recognized,State Government,None,Class 1,Class 5,C.B.S.E.,904,S0137,SAKHU KHANI GOVERNMENT PRIMARY SCHOOL,Available,0,Available,2,Not Available,Not Available,0,Not Available,Not Available

In [15]:
# Order the results alphabetically by name.
sql = """
SELECT *
FROM school_details d INNER JOIN school_facility_details f 
ON d.EstablishmentCode = f.EstablishmentCode
WHERE SchoolLevel IS "PS" AND IsLibraryAvailable IS "Available"
ORDER BY EstablishmentName ASC
;
"""
# Read the sql query into pandas to view the results
df = pd.read_sql_query(sql, engine)
df.head()

2023-03-14 15:46:43,455 INFO sqlalchemy.engine.Engine
SELECT *
FROM school_details d INNER JOIN school_facility_details f
ON d.EstablishmentCode = f.EstablishmentCode
WHERE SchoolLevel IS "PS" AND IsLibraryAvailable IS "Available"
ORDER BY EstablishmentName ASC
;

2023-03-14 15:46:43,456 INFO sqlalchemy.engine.Engine [raw sql] ()

,index,DistrictName,EstablishmentCode,EstablishmentName,BRCName,CRCName,SchoolLevel,ManagementName,LocalityHabitation,SubdivisionName,ConstituencyName,RevenueBlockName,CivicBodyName,WardName,PostOfficeName,PhoneNo,FaxNo,EmailID,Website,LocatedInRuralOrUrban,DiseCode,EstablishedDate,DistrictHQDistance (in Km),CRCDistance (in Km),BACDistance (in Km),IsRecognized,RecognizedBy,ContactPersonName,LowestClass,HighestClass,BoardName,index,EstablishmentCode,EstablishmentName,IsLibraryAvailable,AvailableBooksCount,IsFireExtgAvailable,ExtinguisherCount,HOIRoomAvailable,IsStaffRoomAvailable,NoofStaffRoom,IsLockerForStaffAvailable,IsSportsStoreRoomAvailable
0,345,East,S0178,AGRIGAON GOVERNMENT PRIMARY SCHOOL,Regu Brc,Dalapchen Government Secondary School,PS,State Govt.,AGRIGAON BUSTY,Rongli,Chujachen,Rongli And Rhenak Forest Blocks,Aritar,Kutitar,Rhenock,9679667988,None,None,None,Urban Area,11040500402,30682,62.0,8.0,18.0,Recognized,State Government HRDD,None,Class 1,Class 5,C.B.S.E.,8,S0178,AGRIGAON GOVERNMENT PRIMARY SCHOOL,Available,60,Available,2,Not Available,Available,1,Not Available,Not Available
1,385,East,S0146,ANKUCHEN GOVERNMENT PRIMARY SCHOOL,Pakyong Brc,Linkey Government Secondary School,PS,State Govt.,ANKUCHEN BUSTY,Pakyong,Gnathang-machong,Machong,Linkey Tarey Thang,Linkey,Bering,9932706821,None,None,None,Urban Area,None,28856,51.0,7.0,45.0,Recognized,State Government,None,Class 1,Class 5,C.B.S.E.,22,S0146,ANKUCHEN GOVERNMENT PRIMARY SCHOOL,Available,300,Available,2,Not Available,Available,1,Not Available,Not Available
2,143,East,S0187,BADONG THANGSING GOVERNMENT PRIMARY SCHOOL,Khamdong Brc,Khamdong Government Senior Secondary School,PS,State Govt.,BADONG THANGSING,Gangtok,Khamdong-singtam,Budang Thangsing,Khamdong,Thangshing,Khamdong,None,None,None,None,Urban Area,None,32601,0.0,2.0,2.0,Recognized,State Government,None,Class 1,Class 5,None,38,S0187,BADONG THANGSING GOVERNMENT PRIMARY SCHOOL,Available,13,Available,2,Not Available,Available,1,Not Available,Not Available
3,457,North,S0067,BAKCHA GOVERNMENT PRIMARY SCHOOL,Kabi Brc,Kalzang Gyatso Government senior Secondary School,PS,State Govt.,SAMDONGCHEN,Mangan,Kabi Lungchuk,Kabi,Kabi Tingda,Tingmo Gaikhana,Kabi,9474982250,None,None,None,Urban Area,105101,38718,42.0,4.0,2.0,Recognized,State government,None,Class 1,Class 5,C.B.S.E.,43,S0067,BAKCHA GOVERNMENT PRIMARY SCHOOL,Available,6,Available,2,Not Available,Available,1,Not Available,Not Available
4,1149,West,S1217,"BAL JYOTI ACADEMY, TIMBURBONG",Soreng Brc,Soreng Government Senior Secondary School,PS,Private (Unaided),TIMBURBONG,Soreng,Soreng-chakung,Tadong,Karchi Mangam,Mangder,Soreng,9733293067,None,None,None,Urban Area,None,36892.62916666667,100.0,4.0,4.0,Recognized,HRDD,None,Class 1,Class 5,None,45,S1217,"BAL JYOTI ACADEMY, TIMBURBONG",Available,0,Available,0,Not Available,Available,1,Available,Available